# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsure < Formula
  desc "Helps setting aws cli credentials with azure login"
  homepage "https://github.com/vahid-haghighat/awsure"
  version "1.4.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/vahid-haghighat/awsure/releases/download/v1.4.0/awsure_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "04dae4ae24fabc64935d760b724c18175a8d27d7eaf5c7f12eef8fe3f41177d3"

      def install
        bin.install "awsure"
      end
    end
    on_arm do
      url "https://github.com/vahid-haghighat/awsure/releases/download/v1.4.0/awsure_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "7760d7430825136531ecf866a1897394db26c7b113857bc206b30fc23759fb66"

      def install
        bin.install "awsure"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vahid-haghighat/awsure/releases/download/v1.4.0/awsure_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "cf10e48694d175821f5328f890ac77c43b0b085ad474d48c9dea09e9b029fe8a"

        def install
          bin.install "awsure"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vahid-haghighat/awsure/releases/download/v1.4.0/awsure_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "173f081b4cce8188ce48248506a311b7fc9a88d9a4a5bc35cc8ce58cf1194f1d"

        def install
          bin.install "awsure"
        end
      end
    end
  end

  test do
    system "#{bin}/awsure --version"
  end
end
