# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsure < Formula
  desc "Helps setting aws cli credentials with azure login"
  homepage "https://github.com/vahid-haghighat/awsure"
  version "1.3.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/vahid-haghighat/awsure/releases/download/v1.3.0/awsure_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "a797433aef73ee7c6285a8ee0f686813311342232544830a919f39da8046d52c"

      def install
        bin.install "awsure"
      end
    end
    on_arm do
      url "https://github.com/vahid-haghighat/awsure/releases/download/v1.3.0/awsure_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "b04d129a1f05b3c3d934826017367198ad9318cae55a4882c77d4f4c91ca6e64"

      def install
        bin.install "awsure"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vahid-haghighat/awsure/releases/download/v1.3.0/awsure_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "5e17b641d778d84c6e61e715827fb55bb48319320d5d45fc3b28016902e3232f"

        def install
          bin.install "awsure"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vahid-haghighat/awsure/releases/download/v1.3.0/awsure_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "f9bcef4767c66d72325ca899b1b5d7531583deba1e5ef8059ad6d8487b3da148"

        def install
          bin.install "awsure"
        end
      end
    end
  end

  test do
    system "#{bin}/awsure --version"
  end
end
